spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nursing-liwan-0603?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: huangsiyu@168
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8112
mybatis-plus:
  mapper-locations: classpath:mapper/xml/*Mapper.xml
  type-aliases-package: com.syh.demo.swagger2.authentication.entity

swagger:
#  enable: false
  production: true
  basic:
    enable: true
    username: admin
    password: admin