spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://111.229.247.140:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: huangsiyu@168
      driver-class-name: com.mysql.jdbc.Driver

    test2:
      jdbc-url: jdbc:mysql://111.229.247.140:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: huangsiyu@168
      driver-class-name: com.mysql.jdbc.Driver





