spring:
  datasource:
    url: jdbc:mysql://ip:port/database?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:com/syh/demo/springboot/quartz/mapper/*.xml
  type-aliases-package: com.syh.demo.springboot.quartz.entity
server:
  port: 8099