
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/personal?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: huangsiyu@168
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations:
  - classpath:com/syh/demo/springboot/quartz/mapper/xml/*.xml

server:
  port: 8081