spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: huangsiyu@168
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8812
mybatis-plus:
  type-aliases-package: com.syh.demo.mybatis.plus.springboot.basemapper.entity
#  mapper-locations: com.syh.demo.mybatis.plus.springboot.basemapper.mapper/*.xml
  mapper-locations: classpath:mapper/*.xml
