spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: huangsiyu@168
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8812
